### ISSUE TITLE
Añadir estilos

### ISSUE THREAD

**Issue by Eraledm** [Eraledm/PruebaRepositorio#2]
Neceistamos añadir estilos a la pagina

**Comment by Eraledm** [comment]
Recuerden añadirlo dentro del archivo con un `<style></style>`

**Comment by DaFox416** [comment]
Que sea de color verde

**Comment by gfdfranco** [comment]
Mejor azul

**Comment by Eraledm** [comment]
@DaFox416  si, mejor azul porque son los colores de la empresa
